### ISSUE TITLE
[Question] What is the scale factor for?

### ISSUE THREAD

**Issue by victorhazbun** [palkan/n_plus_one_control#32]
Can you please explain what is the scale factor for?

Thanks.

**Comment by palkan** [comment]
The way n_plus_one_control works is the following:
- We define a test example and the population code (`populate` block)
- Then, the test example executed **twice**, and the difference between the number of executed SQL queries is calculated—if there is a difference, we have an N+1 problem
- The scale factor is used in the population code (it's passed to the block as the first argument): usually, we need to generate different _data sets_ (of different size) to "catch" the difference.

So, if we take a look at the example in Readme:

```ruby
context "N+1", :n_plus_one do
  # Here is how we use scale factors: we generate the different number of records
  # (assuming that the code above load them all and potentially load the children associations
  #  thus producing N+1)
  populate { |n| create_list(:post, n) }

  specify do
    expect { get :index }.to perform_constant_number_of_queries
  end
end
```
