### ISSUE TITLE
[question] Not support Mongoid now?

### ISSUE THREAD

**Issue by xfyuan** [palkan/n_plus_one_control#43]
n_plus_one_control not support mongoid now, right? Is there any plan to support it in future?

**Comment by palkan** [comment]
I'm not familiar with Mongoid.

Does it provides ActiveSupport Notifications events? If so, you can try setting `NPlusOneControl.event = "query.mongoid"` (or whatever) and see how this would work out.

We plan to adapterize the potential N+1 sources in the next major release; it would be great, if you help us with providing some insights on how Mongoid works.

**Comment by xfyuan** [comment]
got it
