### ISSUE TITLE
Tried to create Proc object without a block

### ISSUE THREAD

**Issue by bibendi** [palkan/n_plus_one_control#44]
## What did you do?

Run tests on Ruby 3

## What actually happened?

Got an error `ArgumentError (tried to create Proc object without a block)`
at https://github.com/palkan/n_plus_one_control/blob/eb3a85192e444aa09b39318bec305b9a07246412/lib/n_plus_one_control/rspec/dsl.rb#L23

## Environment

**Ruby Version:** 3.0.0

**Framework Version (Rails, whatever):** rspec, rails 6.1

**N Plus One Control Version:** 0.6.0

**Comment by palkan** [comment]
Fixed by https://github.com/palkan/n_plus_one_control/commit/888e1f6ac46f56521b8afc2ae82a771044ae0cb3
