### ISSUE TITLE
Allow defining `let` in populate

### ISSUE THREAD

**Issue by andresespinosapc** [palkan/n_plus_one_control#48]
## Is your feature request related to a problem? Please describe.

I want to test a `show` endpoint instead of `index`, so the request is specific to a record and I define it on a `let` variable.

## Describe the solution you'd like

To allow defining a different `let` variable each time the populate block is called.

## Describe alternatives you've considered

The only way I found is to directly use `Record.last` when making the request, but it doesn't work if I use it from a `let` variable. This is not very clean nor DRY.

**Comment by palkan** [comment]
Could you please provide an example test code? That would help us to come out with a proper API.

**Comment by gagalago** [comment]
for now, we have to do (see `Page.first` in the expect):
```ruby
populate { |number| create_list(:pages_work, number, page: create(:page)) }
it "doesn't trigger n+1 query" do
  expect { get "/pages/#{Page.first.id}/pages_works" }.to perform_constant_number_of_queries
end
```
it can be great if we can do
```ruby
let(:page) { create(:page)
populate { |number| create_list(:pages_work, number, page: page) }
it "doesn't trigger n+1 query" do
  expect { get "/pages/#{page.id}/pages_works" }.to perform_constant_number_of_queries
end
```
or at least
```ruby
populate do |number| 
  let(:page) { create(:page)
  create_list(:pages_work, number, page: page)
end
it "doesn't trigger n+1 query" do
  expect { get "/pages/#{page.id}/pages_works" }.to perform_constant_number_of_queries
end
```

**Comment by gagalago** [comment]
by writing the previous comment, I just realize what is the solution:
```ruby
let(:page) { create(:page) }
before { page } # force creation at this point
populate { |number| create_list(:pages_work, number, page: page) }
it "doesn't trigger n+1 query" do
  expect { get "/pages/#{page.id}/pages_works" }.to perform_constant_number_of_queries
end
```
the trick is that you have to ensure that data that need to be the same in different scale are persisted before the call to `populate`, otherwise due to the lazy nature of `let` that will be done in the `populate` that is reverted (thanks to transaction) between each scale factor test.
for that you have to either force creation in a `before` block or use `let!`.

**Comment by palkan** [comment]
Thanks for examples!

But who does `before` solves the problem? I though you wanted `let` to be reset between executions within a matcher; but since you're using the same record, you should be find without forcing the creation.

**Comment by palkan** [comment]
Thanks for the explanation!
Added an example to the docs.

Unfortunately, trying to automagically hack around RSpec memoization (`let`) could bring more problems, so we'd prefer to avoid this.
